---
- name: Install unzip package
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Download Terraform binary
  get_url:
    url: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
    dest: /tmp/terraform.zip
    mode: '0644'

- name: Unzip Terraform binary
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'

- name: Ensure Terraform binary is executable
  file:
    path: /usr/local/bin/terraform
    mode: '0755'
    state: file